// <auto-generated />
namespace aspnet_mvc_real_estate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddThumbToProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddThumbToProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202304301120536_AddThumbToProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
