// <auto-generated />
namespace aspnet_mvc_real_estate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateUser11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateUser11));
        
        string IMigrationMetadata.Id
        {
            get { return "202304051345484_updateUser-1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
