//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspnet_mvc_real_estate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collections_galery
    {
        public int collections_id { get; set; }
        public int collections_galery_id { get; set; }
        public string img { get; set; }
    
        public virtual collection collection { get; set; }
    }
}
