//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspnet_mvc_real_estate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class collection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public collection()
        {
            this.collections_galery = new HashSet<collections_galery>();
            this.products = new HashSet<product>();
        }

        public int collections_id { get; set; }
        [Required(ErrorMessage = "Tên dự án không được để trống")]
        [Display(Name = "Tên dự án")]
        public string collections_name { get; set; }
        public string collections_slug { get; set; }
        [Required(ErrorMessage = "Tổng quan dự án không được để trống")]
        [Display(Name = "Tổng quan dự án")]
        public string overview { get; set; }
        [Required(ErrorMessage = "Video không được để trống")]
        [Display(Name = "Video dự án")]
        public string video { get; set; }
        [Required(ErrorMessage = "Giới thiệu không được để trống")]
        [Display(Name = "Giới thiệu dự án")]
        public string introduction { get; set; }
        [Display(Name = "Thông tin dự án")]
        [Required(ErrorMessage = "Thông tin không được để trống")]
        public string information { get; set; }
        [Required(ErrorMessage = "Vị trí dự án không được để trống")]
        [Display(Name = "Vị trí dự án")]
        public string location { get; set; }
        [Display(Name = "Ảnh Thumbnail")]
        public string Thumbnail { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<collections_galery> collections_galery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
    }
}
