//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspnet_mvc_real_estate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mvc_real_estate_db_entity : DbContext
    {
        public mvc_real_estate_db_entity()
            : base("name=mvc_real_estate_db_entity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<collection> collections { get; set; }
        public virtual DbSet<collections_galery> collections_galery { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<news_comment> news_comment { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<products_galery> products_galery { get; set; }
        public virtual DbSet<subscribed> subscribeds { get; set; }
    }
}
