//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspnet_mvc_real_estate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class news
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public news()
        {
            this.news_comment = new HashSet<news_comment>();
        }

        public int news_id { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên bài viết")]
        [Display(Name = "Tên bài viết")]
        public string news_name { get; set; }
        public string news_slug { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập nội dung")]
        [Display(Name = "Nội dung")]
        public string content { get; set; }
        [Display(Name = "Ảnh thumb")]
        public string thumbnail { get; set; }
        [Display(Name = "Ngày đăng")]
        public System.DateTime postdate { get; set; } = DateTime.Now;
        [Display(Name = "Lượt xem")]
        public int viewCount { get; set; } = 0;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<news_comment> news_comment { get; set; }
    }
}
