//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspnet_mvc_real_estate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.products_galery = new HashSet<products_galery>();
        }

        public int products_id { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên bất động sản")]
        [Display(Name = "Tên bất động sản")]
        public string products_name { get; set; }
        public string products_slug { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập diện tích")]
        [Display(Name = "Diện tích")]
        public string area { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name = "Thông tin")]
        public string information { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên Mô tả")]
        [Display(Name = "Mô tả")]
        public string desciption { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập địa chỉ")]
        [Display(Name = "Địa chỉ")]
        public string address { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá")]
        [Display(Name = "Giá")]
        public decimal price { get; set; }
        [Display(Name = "Loại bất động sản")]
        public int type { get; set; }
        [Display(Name = "Lượt xem")]
        public int viewCount { get; set; } = 0;
        [Display(Name = "Nổi bật")]
        public bool isHot { get; set; } = false;
        public int collections_id { get; set; }

        public virtual collection collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<products_galery> products_galery { get; set; }
    }
}
